'''
Created on Jul 20, 2016

@author: Max
'''
from WebLibs import connect,send,receive

IP = #IP ADDRESS HERE
PORT = #PORT NUMBER HERE


#CONNECTION INFORMATION HERE

#ACCEPT GET REQUEST FROM USER AS INPUT HERE

#SEND REQUEST TO WEB SERVER HERE

#GET RESPONSE FROM WEB SERVER HERE

#PRINT RESPONSE HERE
    